version: '2'


services:
  logservice1:
    build:
      context: .
      dockerfile: DockerfileLogservices
    container_name: web
    ports:
      - "34001:6000"
  logservice2:
    build:
      context: .
      dockerfile: DockerfileLogservices
    container_name: web
    ports:
      - "34002:6000"
  logservice3:
    build:
      context: .
      dockerfile: DockerfileLogservices
    container_name: web
    ports:
      - "34003:6000"
  web:
    build:
      context: .
      dockerfile: DockerfileRoundrobin
    container_name: web
    ports:
      - "8087:6000"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:
